global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
    # Jan 23 2026: KA - modified this line and commented so it works for docker as well non-docker install/setup (localhost:8000)
      - targets: ['localhost:8000', 'app:8000']
    #  - targets: ['app:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
